# parameters associated with dataset
datasets:
    # this is the ANI1x released dataset
    dataset_path: '/home/ignacio/Datasets/ani1x_release_wb97x_dz.h5'
    batch_size: 2048
    split_percentage: 0.8
    nonstandard_keys : 
        species: 'species'
        coordinates: 'coordinates'
        energies: 'energies'

# general parameters
general:
    early_stopping_lr: 1.0e-10
    max_epochs: 3000
    use_tqdm: False

loss:
    class: 'RootAtomsLoss'

optimizer:
    class: 'AdamW'
    lr: 0.0001
    betas: [0.9, 0.999]
    weight_decay: 1.0e-7
    amsgrad: False
    eps: 1.0e-8

lr_scheduler:
    class: 'ReduceLROnPlateau'
    patience: 40
    threshold: 6.e-4
    factor: 0.5

validation_function: 'validate_energies'

init:
    function: 'init_sharp_gaussian'


# These hyperparameters are used for constructing the different parts of the
# TemplateModel, the class needs to be specified, along with a list of all the
# hyperparameters for that class

# no custom class is supported for this at the moment
species_converter:
    species: ['H', 'C', 'N', 'O']

# AEVComputer Hyperparameters
# Note that the classmethod "cover_linearly" is called for this class, 
# for all other classes the normal constructor is called
aev_computer:
    class: 'AEVComputer'  
    radial_cutoff: 5.2000e+00
    angular_cutoff: 3.5000e+00
    radial_eta: 16.0
    angular_eta: 8.0
    radial_dist_divisions: 16
    angular_dist_divisions: 4
    zeta: 32.0
    angle_sections: 8
    num_species: 4
    radial_start: 0.9000e+00
    angular_start: 0.9000e+00

# ANIModel Hyperparameters
ani_model:
    class: 'ANIModelMultiple'
    squeeze_last: True

# AtomicNetwork Hyperparameters
atomic_network:
    class: 'AtomicNetworkAttention'
    dim_in: 384
    num_heads: 3

# no custom class is supported for this at the moment
energy_shifter:
    num_species: 4
