datasets:
  dataset_path: rxn/
  batch_size: 2048
  split_percentage: 0.8
  nonstandard_keys:
    species: species
    coordinates: coordinates
    energies: energies
general:
  early_stopping_lr: 1.0e-10
  max_epochs: 3000
loss:
  class: RootAtomsLoss
optimizer:
  class: AdamW
  lr: 0.0008
  betas:
  - 0.9
  - 0.999
  weight_decay: 6.0e-05
  amsgrad: false
  eps: 1.0e-08
lr_scheduler:
  class: CosineAnnealingWarmRestarts
  eta_min: 0.0
  T_0: 130
validation_function: validate_energies
init:
  function: init_sharp_gaussian
species_converter:
  species:
  - H
  - C
  - N
  - O
aev_computer:
  class: AEVComputerJoint
  radial_cutoff: 5.2
  angular_cutoff: 3.5
  radial_eta: 16.0
  angular_eta: 8.0
  radial_dist_divisions: 16
  angular_dist_divisions: 4
  zeta: 32.0
  angle_sections: 8
  num_species: 4
  radial_start: 0.9
  angular_start: 0.9
ani_model:
  class: ANIModelMultiple
  squeeze_last: true
atomic_network:
  class: AtomicNetworkGELU
  dim_in: 384
  dims:
  - 128
  - 112
  - 96
  final_layer_bias: true
energy_shifter:
  num_species: 4
